### PR TITLE
Automate release workflows

### PR DESCRIPTION
**Pull request by kylelaker**
This refactors our release workflow to always pull in main and then push to both `main` and `develop`. `develop` will also get a bump to the _next_ prepatch version. Then, we add support to publish to both GitHub Packages and to NPM.

This is a [new feature](https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/) for branch protection rules.

### CODE REVIEW

**Comment by kylelaker** [comment]
Honestly, I don't really know how we go about testing this...

**Comment by kylelaker** [comment]
Using this updated workflow also means that we have to authorize @easy-dynamics-oscal-automation to push to `develop` and `main` without a pull request.

**Review by hreineck — APPROVED** [review]

**Comment by hreineck** [comment]
> Using this updated workflow also means that we have to authorize @easy-dynamics-oscal-automation to push to `develop` and `main` without a pull request. I am mostly okay with that. The alternative seems to either be a large series of pull requests (which will all require 2 reviews) or using a service account with a PAT which feels messier even.

I agree, authorizing the automation account is probably the cleanest option

**Comment by hreineck** [comment]
> Honestly, I don't really know how we go about testing this...

In the past we set up a dummy release and manually triggered the workflow

**Review by mikeisen1 — APPROVED** [review]

**Pull request merged**
