### PR TITLE
Display SSP Authz Boundary

### LINKED ISSUE #225: Display SSP Authorization Boundary
As a user of the OSCAL Viewer, I want to see the Authorization Boundary of a System Security Plan ([example](https://github.com/GSA/fedramp-automation/blob/master/dist/content/templates/ssp/json/FedRAMP-SSP-OSCAL-Template.json#L823)) including any specified inline images so that I can understand the scope of the ATO.

### Acceptance Criteria
- A Authorization Boundary section is displayed in System Characteristics if present in the OSCAL SSP
- The Authorization Boundary`description` field is displayed
- The Authorization Boundary `remarks` is displayed
- Any Authorization Boundary diagram images are displayed with any defined caption

### Implementation Notes
- We're likely to develop a Diagram component that can be re-used across Authorization Boundary, Network Architecture, and Data Flow components
- We could potentially modify the existing `oscal-rest-service` [test SSP](https://github.com/EasyDynamics/oscal-rest-service/blob/develop/oscal-data-repository-commons-tests/src/main/resources/oscal-content/system-security-plans/ssp-example.json) to include an authorization boundary section pointing to an actual image, but any example SSP with that data will suffice

### Subtasks
- [x] Add OSCALDiagram component
- [x] Add display of OSCALDiagram authz boundary to SSP
- [x] Add authz boundary segment and diagram to test data in REST service
- [x] EasyDynamics/oscal-rest-service#49

### PR DESCRIPTION
**Pull request by rgauss**
Closes #225

If looking to do manual testing of this you can run the app in REST mode with pointing to a service with changes in EasyDynamics/oscal-rest-service#49

### CODE REVIEW

**Comment by kylelaker** [comment]
> If looking to do manual testing of this you can run the app in REST mode with pointing to a service with changes in

I assume (based on the implementation here) that running in REST mode isn't necessarily required so long as you have an SSP with a _valid_ href for an authorization boundary diagram (which none of the examples currently do)?

**Comment by rgauss** [comment]
> > If looking to do manual testing of this you can run the app in REST mode with pointing to a service with changes in
> 
> I assume (based on the implementation here) that running in REST mode isn't necessarily required so long as you have an SSP with a _valid_ href for an authorization boundary diagram (which none of the examples currently do)?

Correct, I thought about creating a gist for testing but figured reviewers should be looking at the REST side anyway.

**Comment by rgauss** [comment]
VS Code did something weird with the rebase here.

**Comment by rgauss** [comment]
Hopefully fixed this in #255

**Pull request closed without merging**
