### PR TITLE
fix(prose): newline characters not displaying properly

### LINKED ISSUE #619: Control Prose not displaying newline characters properly
### Description

Control prose do not properly display line breaks despite `\n` being written in prose. 

```
{
  "id": "sr-2.1_asm-examine",
  "name": "assessment-method",
  "props": [
    {
      "name": "method",
      "ns": "http://csrc.nist.gov/ns/rmf",
      "value": "EXAMINE"
    },
    {
      "name": "label",
      "value": "SR-02(01)-Examine",
      "class": "sp800-53a"
    }
  ],
  "parts": [
    {
      "name": "assessment-objects",
      "prose": "Supply chain risk management policy\n\nsupply chain risk management procedures\n\nsupply chain risk management team charter documentation\n\nsupply chain risk management strategy\n\nsupply chain risk management implementation plan\n\nprocedures addressing supply chain protection\n\nsystem security plan\n\nprivacy plan\n\nother relevant documents or records"
    }
  ]
},
```

### Environment

OSCAL Viewer

### Steps to Reproduce

Go to https://oscal-viewer.msd.easydynamics.com/profile/?url=https://raw.githubusercontent.com/EasyDynamics/oscal-demo-content/main/profiles/NIST_SP-800-53_rev5_MODERATE-baseline_profile.json and scroll down to `SR-2.1 Establish SCRM Team`.

### Expected behavior

`SR-02(01)` text is displayed with new lines to separate content. 

### Actual Behavior

image

### Additional Notes

I unfortunately have not been able to look into this bug a ton. But it seems it may be related to `"assessment-objects"` specifically.

### PR DESCRIPTION
**Pull request by mpemy**
The MarkupMultine method is used instead of the Markuline in the getTextSegment method because this is where we handle prose part. However, this method add an empty line at the begining which does not align well with the placeholder label. This empty line should be remove.

Just address a typo that was mistakenly inserted in the last commit.

closes #619

### CODE REVIEW

**Comment by Bronstrom** [comment]
Posting an up-to-date screenshot of SR-2.1 for convenience:

image

**Review by kylelaker — COMMENTED** [review]
Can we just handle this in `getTextSegment` itself?

```tsx
function getTextSegment(text, key) {
  if (!text) {
    return null;
  }
  return (
    <Typography component="span" key={key}>
      {
        text.includes("\n") ?
        <OSCALMarkupMultiline>{text}</OSCALMarkupMultiline> :
        <OSCALMarkupLine>{text}</OSCALMarkupLine>
      }
    </Typography>
  );
}
```

**Comment by mpemy** [comment]
Thanks Kyle, I will do, I will handle that logic in getTextSegment.
Thanks for your suggestions.

**Review by kylelaker — APPROVED** [review]
Thanks for your work on this!!

**Review by tuckerzp — APPROVED** [review]

**Pull request merged**
