### PR TITLE
Improve Profile Viewer performance & user experience

### LINKED ISSUE #74: Improve Profile Viewer Performance/Loading Display
As a user of the OSCAL viewer app or underlying React components, I want Profiles to be resolved and displayed in a timely manner so that my workflow is not disturbed by waiting for the page to load.

### Acceptance Criteria
* The Profile viewer loads the [FedRAMP moderate profile](https://raw.githubusercontent.com/GSA/fedramp-automation/master/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline_profile.json) in 2 seconds or less in the live sandbox environment
* If the complete rendering takes longer than 0.5 seconds a loading indicator should be displayed for any area taking time to render

### Implementation Notes
* The [Material-UI Skeleton component ](https://material-ui.com/components/skeleton/) should be considered
* Note that we’ll address any loading indicator additions to other viewers in a future issue

### PR DESCRIPTION
**Pull request by Bronstrom**
Due to lengthy rendering, the Profile Viewer takes a long period of time to show elements on the page. In order to improve the user experience, a skeleton framework has been added to display on the page while rendering the resolved controls. To improve performance, a few areas of `OSCALProfile`, `OSCALControl`, & underlying components have been optimized. Most notably, the `modifications` data sent between components have been slimmed down.

- resolves #74

### CODE REVIEW

**Comment by Bronstrom** [comment]
I wanted to note the [live sandbox environment](https://oscal-viewer.msd.easydynamics.com/profile) seemed to already run the [FedRAMP moderate profile](https://raw.githubusercontent.com/GSA/fedramp-automation/master/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline_profile.json) in about 2 or less seconds (as desired in the Acceptance Criteria). There seems to be a performance drop with it locally, especially when using the reload button after a few times. I was able to shave a couple seconds off when running it locally - which I think will still show a noticeable change on AWS.

**Review by kkennedy26 — COMMENTED** [review]
image

I got this error when running locally and clicking to the profile viewer.

**Comment by Bronstrom** [comment]
> I got this error when running locally and clicking to the profile viewer.

@kkennedy26 I was using the FedRAMP profile as the default profile when testing. I just realized the NIST profile doesn't have `set-parameters`. I'll make a fix for this.

**Comment by kylelaker** [comment]
This looks great and I am really excited about the potential improvements here! There are a lot of changes. Can you talk about how specifically this was optimized? Are there performance benefits to `function` over `const X = () => {}`?

**Comment by Bronstrom** [comment]
> This looks great and I am really excited about the potential improvements here! There are a lot of changes. Can you talk about how specifically this was optimized? Are there performance benefits to `function` over `const X = () => {}`?

Of course - I was a bit vague about optimization. The arrow functions (`const X = () => {}`) create a new function every time components are re-rendered. To avoid this, the "function" keyword can be used instead. Arrow functions are apparently good in less dynamic contexts. For more information see: [5 Ways to Optimize Your Functional React Components - Avoid arrow functions when possible](https://javascript.plainenglish.io/5-ways-to-optimize-your-functional-react-components-cb3cf6c7bd68#:~:text=1.%20Avoid%20arrow%20functions%20when%20possible) and [When (and why) you should use ES6 arrow functions](https://www.freecodecamp.org/news/when-and-why-you-should-use-es6-arrow-functions-and-when-you-shouldnt-3d851d7f0b26/). I also made the choice to split up the modification attributes, `set-parameters` from `alters`, to lessen the amount of data shared between underlying components. This should help with the efficiency of `OSCALControlProse` and `OSCALControlModifications`, which are doing a lot of the work.

**Comment by kkennedy26** [comment]
Looks good. Can definitely see the improvements in load time with Profile Viewer since the recent commit

**Comment by Bronstrom** [comment]
To further improve performance, I had the idea that more data could be filtered out of modifications (it appears to be what's taking the longest time to load and render), such as getting rid of the `removes` attribute in `modify.alter`. Although, we will probably be using this data soon in a future issue ([EGRC-407](https://easydynamics.atlassian.net/jira/software/projects/EGRC/boards/86/backlog?selectedIssue=EGRC-407)). I was also looking into `useMemo()` and `useCallback()`, but there doesn't seem to be a function that's being relatedly rendered in the same exact way (like with how the control IDs parameter is different for rendering the majority of functions) or they would minimally help. The functions I attempted these on seemed to have a lot of overhead causing the Profile Viewer to stagnate more. Let me know if anyone has a different opinion or guidance on this.

**Review by kylelaker — APPROVED** [review]

**Review by kkennedy26 — APPROVED** [review]
Just realized I didn't approve this in my previous comment but meant to haha.. good work

**Pull request merged**
